In [4]:
import pandas as pd
data = pd.read_csv("/content/train.csv")
target_variable = "price_range"
features = data.drop(columns=[target_variable])
print("Features:")
print(features.head())
print("\nTarget Variable:")
print(data[target_variable].head())

Features:
   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0

In [15]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()
normalized_features = scaler.fit_transform(features)


print("Normalized Features:")
print(normalized_features[:5])

Normalized Features:
[[0.22778891 0.         0.68       0.         0.05263158 0.
  0.08064516 0.55555556 0.9        0.14285714 0.1        0.01020408
  0.17089453 0.61277392 0.28571429 0.38888889 0.94444444 0.
  0.         1.        ]
 [0.34736139 1.         0.         1.         0.         1.
  0.82258065 0.66666667 0.46666667 0.28571429 0.3        0.46173469
  0.99332443 0.63468733 0.85714286 0.16666667 0.27777778 1.
  1.         0.        ]
 [0.04141617 1.         0.         1.         0.10526316 1.
  0.62903226 0.88888889 0.54166667 0.57142857 0.3        0.64438776
  0.811749   0.6272047  0.42857143 0.11111111 0.38888889 1.
  1.         0.        ]
 [0.0761523  1.         0.8        0.         0.         0.
  0.12903226 0.77777778 0.425      0.71428571 0.45       0.62040816
  0.85847797 0.67156601 0.78571429 0.44444444 0.5        1.
  0.         0.        ]
 [0.88176353 1.         0.28       0.         0.68421053 1.
  0.67741935 0.55555556 0.50833333 0.14285714 0.7        0.61632653

In [18]:
from sklearn.model_selection import train_test_split

# Splitting the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print(f"Train data shape: X_train={X_train.shape}, y_train={y_train.shape}")
print(f"Test data shape: X_test={X_test.shape}, y_test={y_test.shape}")



Train data shape: X_train=(1600, 20), y_train=(1600,)
Test data shape: X_test=(400, 20), y_test=(400,)


In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [22]:
df = pd.read_csv('/content/train.csv')

In [23]:
X = df.drop('price_range', axis=1)
y = df['price_range']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [25]:
model = LogisticRegression()


In [29]:
y_pred = model.predict(X_test)

In [28]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print("Confusion Matrix:")
print(conf_matrix)


Accuracy: 0.63
Precision: 0.64
Recall: 0.63
Confusion Matrix:
[[79 25  1  0]
 [17 46 20  8]
 [ 0 17 46 29]
 [ 0  1 29 82]]
